# Generated by Django 2.1.7 on 2019-03-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcsvadmin', '0002_auto_20190327_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
