# Generated by Django 2.1.7 on 2019-03-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171024_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'Admin'), (2, 'Super Admin'), (5, 'School Admin'), (6, 'School Super Admin'), (3, 'Teacher'), (4, 'Student')], default=2),
        ),
    ]
